version: '3.1'

services:
  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: developer

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: local
      ME_CONFIG_MONGODB_ADMINPASSWORD: developer
